apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-mysql-eh
  labels:
    strimzi.io/cluster: kafka-connect-eh
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: mysql
    database.port: 3306
    database.user: ${secrets:debezium-eh/debezium-secret:username}
    database.password: ${secrets:debezium-eh/debezium-secret:password}
    database.server.id: 184054
    topic.prefix: mysql
    database.include.list: inventory
    # schema.history.internal.kafka.bootstrap.servers: debezium-cluster-kafka-bootstrap:9092
    # schema.history.internal.kafka.topic: schema-changes.inventory